package:
    name: fiona
#    version: 1.7.10.post1
    version: 1.8.0

source:
    git_url: https://github.com/Toblerity/Fiona.git
#    git_tag: 1.7.10.post1
    git_tag: 1.8.0

build:
    number: 1
    preserve_egg_dir: True
    entry_points:
        - fio=fiona.fio.main:main_group

requirements:
    build:
        - python
        - cython
        - setuptools
        - gdal
        - numpy
        - munch
        - click-plugins
#        - enum34
    run:
        - python
        - setuptools
        - cligj
        - munch
        - click-plugins
        - six
        - gdal
        - numpy
#        - enum34

test:
    imports:
        - fiona
        - fiona.fio
    commands:
        - fio --help
    requires:
        - attr
        - nose
    files:
        - test.cpg
        - test.dbf
        - test.shp
        - test.shx

about:
    home: http://github.com/Toblerity/Fiona
    license: BSD License
    summary: 'Fiona reads and writes spatial data files'
