package:
  name: hdf5
  version: 1.10.4

source:
  fn: hdf5-1.10.4.tar.gz
  url: https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.4.tar.gz

build:
  number: 1

requirements:
  build:
    - zlib
#    - mpich
#    - gcc

  run:
    - zlib
#    - mpich
#    - libgcc

about:
  home: https://www.hdfgroup.org/HDF5/
  license: BSD-like
  summary: HDF5 is a data model, library, and file format for storing and managing data.
