package:
  name: libnetcdf
  version: 4.3.2

build:
  number: 1
  string: esmf
  rpaths:
    - lib/
    - lib64/

source:
  fn: v4.3.2.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/v4.3.2.tar.gz

requirements:
  build:
    - curl
    - zlib
    - hdf5 1.8.14 esmf
    - gcc 4.8.2 esmf
    - gmp
    - mpc
    - mpfr
  run:
    - curl
    - zlib
    - hdf5 1.8.14 esmf
    - gcc 4.8.2 esmf
    - gmp
    - mpc
    - mpfr

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  summary: NetCDF is a set of software libraries and self-describing, machine-independent data formats that support the creation, access, and sharing of array-oriented scientific data.