package:
    name: ugrid-tools
    version: next

source:
    git_url: https://github.com/NESII/ugrid-tools.git
    git_tag: next

build:
    number: 0
    skip: True # [osx]
    skip: True # [win]
    skip: True # [py3k]

requirements:
    build:
        - python >=2.7,<3
        - setuptools
        - fiona
        - netcdf4
        - shapely
        - mpi4py
        - esmpy
        - rtree
    run:
        - python
        - fiona
        - netcdf4
        - shapely
        - mpi4py
        - esmpy
        - rtree
        - logbook

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.
