package:
  name: mpi4py
  version: 2.0.0

source:
  git_url: https://bitbucket.org/mpi4py/mpi4py.git
  git_tag: 2.0.0

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython
    - mpich
  run:
    - python
    - setuptools
    - cython
    - mpich

about:
  home: http://mpi4py.scipy.org/
  license: BSD
  summary: This package provides Python bindings for the Message Passing Interface (MPI) standard.
