package:
  name: mpi4py
  version: 1.3.1

source:
  fn: mpi4py-1.3.1.tar.gz
  url: https://pypi.python.org/packages/source/m/mpi4py/mpi4py-1.3.1.tar.gz

build:
  number: 1
  rpaths:
    - lib/
    - lib64/
  string: esmf

requirements:
  build:
    - python
    - openmpi 1.8.4 esmf #[osx]
    - mpich2 #[linux]

  run:
    - python
    - openmpi 1.8.4 esmf #[osx]
    - mpich2 #[linux]

about:
  home: http://mpi4py.scipy.org/
  license: BSD
  summary: This package provides Python bindings for the Message Passing Interface (MPI) standard.
