package:
    name: ocgis-next
    version: 1.4.0.dev1

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: next

build:
    number: 4
    skip: True # [osx]
    skip: True # [win]
    skip: True # [py3k]

requirements:
    build:
        - python >=2.7,<3
        - fiona
        - gdal
#        - libgdal
        - netcdf4
        - numpy
        - shapely
        - rtree
        - cf_units
        - icclim ==4.2.5
    run:
        - python
        - fiona
        - gdal
#        - libgdal
        - netcdf4
        - numpy
        - shapely
        - proj.4
        - rtree
        - cf_units
        - krb5
        - icclim ==4.2.5
#        - esmpy==7.0.0  #Optional!

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.
