package:
  name: netcdf-fortran
  version: 4.4.1

build:
  string: 2
  rpaths:
    - lib/
    - lib64/

source:
  fn: netcdf-fortran-4.4.1.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.1.tar.gz

requirements:
  build:
    - libnetcdf
  run:
    - libnetcdf

about:
  home: http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-fortran-install.html
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  summary: Fortran netCDF library.