package:
  name: gmp
  version: 5.1.2

source:
  fn: gmp-5.1.2.tar.bz2
  url: https://ftp.gnu.org/gnu/gmp/gmp-5.1.2.tar.bz2

about:
  home: https://gmplib.org/
  license: GNU LGPL v3 and GNU GPL v2
  summary: GMP is a free library for arbitrary precision arithmetic, operating on signed integers, rational numbers, and floating-point numbers.