package:
  name: gdal
  version: 1.11.2

source:
  fn: gdal-1.11.2.tar.gz
  url: http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
#  md5: 7555f55855f613be49e6508eed0ac3fa
#  patches:
#    - adaguc.patch

build:
  number: 1
  string: ocgis

requirements:
  build:
    - python
    - numpy
#    - xerces-c
    - geos
#    - proj4 ==4.9.1
    - hdf5 ==1.8.14
    - libnetcdf ==4.3.2
#    - libpng
#    - jpeg
#    - udunits
#    - jasper
#    - sqlite
#    - gcc ==4.8.2gfortran
  run:
    - python
    - numpy
#    - xerces-c
    - geos
#    - proj4 ==4.9.1
    - hdf5 ==1.8.14
    - libnetcdf ==4.3.2
#    - libpng
#    - jpeg
#    - udunits
#    - jasper
#    - sqlite
#    - gcc ==4.8.2gfortran

about:
  home: http://www.gdal.org/
  license: MIT
  summary: The Geospatial Data Abstraction Library (GDAL). Built with all command line tools and with GEOS, HDF5, and NetCDF support.
