package:
  name: libnetcdf
  version: 4.4.1

source:
  fn: v4.4.1.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/v4.4.1.tar.gz

requirements:
  build:
    - curl
    - hdf5
    - zlib
  run:
    - curl
    - hdf5
    - zlib

test:
  commands:
    - ncdump
    - nc-config --help

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT