package:
  name: esmpy
  version: 7.0.0

build:
  number: 1

source:
  git_url: git://git.code.sf.net/p/esmf/esmf
  git_tag: ESMF_7_0_0

requirements:
  build:
    - python
    - numpy
    - esmf ==7.0.0
    - mpi4py
  run:
    - python
    - numpy
    - esmf ==7.0.0
    - mpi4py

test:
  requires:
    - nose

about:
  home: https://www.earthsystemcog.org/projects/esmpy/
  license: The University of Illinois/NCSA Open Source License (NCSA)
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.
