package:
    name: netcdf4
    version: {{environ['CBUILD_NETCDF4_PYTHON_VERSION']}}

source:
    git_url: https://github.com/Unidata/netcdf4-python.git
    git_tag: {{environ['CBUILD_NETCDF4_PYTHON_TAG']}}

build:
    number: 1
    string: esmf

requirements:
    build:
      - python
      - setuptools
      - numpy
      - libnetcdf 4.3.2 esmf
      - curl
      - zlib
      - hdf5 1.8.14 esmf
      - gcc 4.8.2 esmf
      - gmp
      - mpc
      - mpfr
    run:
      - python
      - setuptools
      - numpy
      - libnetcdf 4.3.2 esmf
      - curl
      - zlib
      - hdf5 1.8.14 esmf
      - gcc 4.8.2 esmf
      - gmp
      - mpc
      - mpfr
test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.
