package:
  name: netcdf4
#  version: local
#  version: latest
  version: 1.3.1

source:
  git_url: https://github.com/Unidata/netcdf4-python.git
#  git_tag: master
  git_tag: v1.3.1rel
#  path: /home/benkoziol/Dropbox/NESII/project/NESII/netcdf4-python

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - libnetcdf
    - cython
    - gcc
    - mpi4py
  run:
    - python
    - mpi4py
    - libnetcdf
    - numpy
    - cython
    - libgcc
