package:
  name: mpc
  version: 1.0.1

source:
  fn: mpc-1.0.1.tar.gz
  url: ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.1.tar.gz

requirements:
  build:
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

about:
  home: http://www.multiprecision.org/index.php?prog=mpc
  license: GNU Lesser General Public License
  summary: GNU Mpc is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.