package:
    name: ocgis
    version: {{environ['CBUILD_OCGIS_VERSION']}}

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: {{environ['CBUILD_OCGIS_TAG']}}

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4 <={{environ['CBUILD_NETCDF4_PYTHON_VERSION']}}
        - shapely
        - fiona
        - gdal <2.0
    run:
        - python
        - numpy
        - netcdf4 <={{environ['CBUILD_NETCDF4_PYTHON_VERSION']}}
        - shapely
        - fiona
        - gdal <2.0
        - icclim
        - cfunits =={{environ['CBUILD_CFUNITS_VERSION']}}
        - rtree
        - proj4

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.