package:
#    name: ocgis
    name: ocgis-next
#    version: 2.0.0
    version: 2.1.0.dev1

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: master

build:
    number: 3

requirements:
    build:
        - python
        - six
        - numpy
        - gdal 2.1*
        - shapely
        - netcdf4
        - fiona
        - pyproj
    run:
        - python
        - six
        - numpy
        - gdal 2.1*
        - shapely
        - netcdf4
        - fiona
        - pyproj
        - rtree
        - cf_units
        - mpi4py
#        - esmpy==7.0.0  #Optional!
#        - icclim==4.2.5  #Optional!

test:
  requires:
    - nose
    - mock

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    license_file: LICENSE.txt
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.
