package:
  name: esmf
  version: {{environ['CBUILD_ESMF_VERSION']}}

build: 
  number: 0
  rpaths:
    - lib/
    - lib64/
  string: esmf

source:
  git_url: git://git.code.sf.net/p/esmf/esmf
  git_tag: {{environ['CBUILD_ESMF_TAG']}}

requirements:
  build:
    - netcdf-fortran
    - openmpi 1.8.4 esmf # [osx]
    - mpich2
  run:
    - netcdf-fortran
    - openmpi 1.8.4 esmf # [osx]
    - mpich2

about:
  home: http://www.earthsystemmodeling.org/
  license: The University of Illinois/NCSA Open Source License (NCSA)
  summary: The Earth System Modeling Framework (ESMF) is software for building and coupling weather, climate, and related models.