package:
  name: libnetcdf
  version: 4.5.0

source:
  git_url: https://github.com/Unidata/netcdf-c.git
  git_tag: v4.5.0

requirements:
  build:
    - curl
    - hdf5
    - zlib
    - m4
    - gcc
  run:
    - curl
    - hdf5
    - zlib
    - m4
    - libgcc

test:
  commands:
    - ncdump
    - nc-config --help

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT