package:
    name: gdal
    version: 2.3.3

source:
    fn: gdal-2.3.3.tar.gz
    url: http://download.osgeo.org/gdal/2.3.3/gdal-2.3.3.tar.gz

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - numpy
        - geos
        - proj4
        - curl
        - shapely # Force usage of appropriate GEOS.
        - gcc
    run:
        - python
        - setuptools
        - numpy
        - geos
        - proj4
        - curl
        - shapely # Force usage of appropriate GEOS.
        - libgcc

test:
    files:
        - os1_hw.py
        - sites.dbf
        - sites.sbn
        - sites.sbx
        - sites.shp
        - sites.shx
    imports:
        - osgeo
    commands:
        - ogrinfo sites.shp

about:
    home: http://www.gdal.org/
    license: MIT
    summary: 'The Geospatial Data Abstraction Library (GDAL)'
