package:
    name: gdal
    version: 2.1.4

source:
    fn: gdal-2.1.4.tar.gz
    url: http://download.osgeo.org/gdal/2.1.4/gdal-2.1.4.tar.gz
    md5: ae3726c6deb81c01603b3e5680f239d8

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - numpy
        - geos
        - proj4
        - curl
        - shapely # Force usage of appropriate GEOS.
        - gcc
    run:
        - python
        - setuptools
        - numpy
        - geos
        - proj4
        - curl
        - shapely # Force usage of appropriate GEOS.
        - libgcc

test:
    files:
        - os1_hw.py
        - sites.dbf
        - sites.sbn
        - sites.sbx
        - sites.shp
        - sites.shx
    imports:
        - osgeo
    commands:
        - ogrinfo sites.shp

about:
    home: http://www.gdal.org/
    license: MIT
    summary: 'The Geospatial Data Abstraction Library (GDAL) Version 1.11.2. Built with all command line tools and with GEOS and HDF5 support.'
