package:
  name: mpich2
  version: 1.4.1

source:
  fn: mpich2-1.4.1.tar.gz
  url: http://www.mpich.org/static/downloads/1.4.1/mpich2-1.4.1.tar.gz

build:
  number: 0
  string: esmf

about:
  home: https://http://www.mpich.org/
  license: BSD
  summary: MPICH is a high performance and widely portable implementation of the Message Passing Interface (MPI) standard.
