package:
  name: proj.4
  version: 4.9.2

source:
  fn: proj-4.9.2.tar.gz
  url: http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  md5: 9843131676e31bbd903d60ae7dc76cf9

build:
  number: 0

about:
  home: http://trac.osgeo.org/proj/
  license: MIT License
  summary: PROJ.4 is a library for performing conversions between cartographic projections.
