package:
  name: curl
  version: 7.49.1

source:
  fn: curl-7.49.1.tar.gz
  url: https://curl.haxx.se/download/curl-7.49.1.tar.gz

requirements:
  build:
    - pkg-config
    - openssl
    - zlib
  run:
    - openssl

about:
  home: https://curl.haxx.se/
  license: MIT (Modified BSD)
  license_url: https://curl.haxx.se/docs/copyright.html