package:
  name: f90netcdf
  version: 4.4.1

build:
  number: 1
  rpaths:
    - lib/
    - lib64/
  string: esmf

source:
  fn: netcdf-fortran-4.4.1.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.1.tar.gz

requirements:
  build:
    - gcc 4.8.2 esmf
    - gmp
    - mpc
    - mpfr
    - libnetcdf 4.3.2 esmf
  run:
    - gcc 4.8.2 esmf
    - gmp
    - mpc
    - mpfr
    - libnetcdf 4.3.2 esmf

about:
  home: http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-fortran-install.html
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  summary: Fortran netCDF library.